export const ADD_ELEMENT = "ADD_ELEMENT";
export const CHANGE_WIDTH = 'CHANGE_WIDTH';
export const CHANGE_HEIGHT = 'CHANGE_HEIGHT';
export const CHANGE_TOP = 'CHANGE_TOP';
export const CHANGE_LEFT = 'CHANGE_LEFT';
export const ENABLE_ACTIVE = 'ENABLE_ACTIVE';
export const DISABLE_ACTIVE = 'DISABLE_ACTIVE';

export const SET_ACTIVE_ELE_DATA = 'SET_ACTIVE_ELE_DATA';
export const SET_DIS_ALL_ACTIVE_ELE_DATA = 'SET_DIS_ALL_ACTIVE_ELE_DATA';

export default {
  ADD_ELEMENT,
  CHANGE_WIDTH,
  CHANGE_HEIGHT,
  CHANGE_TOP,
  CHANGE_LEFT,
  ENABLE_ACTIVE,
  DISABLE_ACTIVE,
  SET_ACTIVE_ELE_DATA,
  SET_DIS_ALL_ACTIVE_ELE_DATA,
}
